### ISSUE TITLE
Use cmake to manage builds

### ISSUE THREAD

**Issue by odrisci** [JamesTCurran/GNSS-Metadata-Standard#1]
It might be useful to use the [cmake](http://cmake.org) utility to manage builds. The advantage of this is that we could eliminate all the `ide` folders as cmake would manage the auto-generation and update of all the IDE project files. Thus one set of files could be used to manage the build for Linux, Windows and Mac OS X, under a variety of different build environments (Makefiles, Visual Studio, XCode, Code Blocks, Eclipse, etc).

I've created a first simple demonstration of this [here](/odrisci/GNSS-Metadata-Standard/tree/cmake). I've successfully tested this on Ubuntu 15.04 using Unix Makefiles, Windows 10 using Visual Studio 2015 Community Edition and Mac OS X 10.10 Yosemite using both Unix Makefiles and XCode.

I'm not sure how well the current version works with earlier versions of Windows, as the Windows 10 SDK introduced a definition of the `timespec` struct, which meant that I had to update the file `API/source/inc/GnssMetadata/Date.h`. This fix might not work for earlier versions of the Windows SDK.

**Comment by JamesTCurran** [comment]
Hi Cillian,
thanks for the note. I have added your CMakeLists.txt files to a branch of the project. I have just made a few updates: to include new source files; and to conditionally add one TestApp as a target, depending on whether  you cmake from the API dir or the Converter. 
My hope here is that we (or whoever is maintaining the code) can simply pre-generate a bunch of ide directories, for the more common environments, so that users can simply take their preferred, and ignore the others. I hope this will encourage more people to get involved, and to make some contributions.
What do yo think?
James
